guide:
  - title: 品牌
    name: Guide
    items:
      - title: 色彩
        name: Color
components:
  - title: 综述
    name: Docs
    items:
      - title: 介绍
        name: Introduction
      # - title: 安装
      #   name: Installation
      # - title: 快速上手
      #   name: Quickstart
      # - title: 国际化
      #   name: I18n
      # - title: 更新日志
      #   name: Changelog
  - title: 组件
    name: Docs
    groups:
      - title: 基础组件
        items:
          - title: 按钮
            name: Button
      - title: 布局组件
        items:
          - title: 列表
            name: List
          - title: 卡片
            name: Card
          - title: 弹性布局
            name: Flex
          - title: 宫格布局
            name: Grid
          - title: 浮动布局
            name: FloatLayout
<<<<<<< Updated upstream
=======
      - title: 操作反馈
        items:
          - title: 轻提示
            name: Toast
          - title: 模态框
            name: Modal
          - title: 进度条
            name: Progress
          - title: 上拉菜单
            name: ActionSheet
          - title: 活动指示器
            name: ActivityIndicator
>>>>>>> Stashed changes
          # - title: 布局
          #   name: Layout
          # - title: 标签
          #   name: Tag
          # - title: 图标
          #   name: Icon
  #     - title: 表单组件
  #       items:
  #         - title: 多选框
  #           name: Checkbox
  #         - title: 输入框
  #           name: Input
  #         - title: 数字输入框
  #           name: InputNumber
  #         - title: 单选按钮
  #           name: Radio
  #         - title: 评分
  #           name: Rate
  #         - title: 选择器
  #           name: Select
  #         - title: 开关
  #           name: Switch
  #         - title: 滑动输入条
  #           name: Slider
  #         - title: 文本域
  #           name: Textarea
  #     - title: 视图组件
  #       items:
  #         - title: 警告提示
  #           name: Alert
  #         - title: 徽标
  #           name: Badge
  #         - title: 卡片
  #           name: Card
  #         - title: 折叠面板
  #           name: Collapse
  #         - title: 加载进度条
  #           name: LoadingBar
  #         - title: 模态框
  #           name: Modal
  #         - title: 全局提示
  #           name: Message
  #         - title: 通知提醒
  #           name: Notification
  #         - title: 进度条
  #           name: Progress
  #         - title: 弹出框
  #           name: Popover
  #         - title: 文字提示
  #           name: Tooltip
  #         - title: 时间轴
  #           name: Timeline
  #         - title: 表格
  #           name: Table

  #     - title: 导航组件
  #       items:
  #         - title: 面包屑
  #           name: Breadcrumb
  #         - title: 下拉菜单
  #           name: Dropdown
  #         - title: 导航菜单
  #           name: Menu
  #         - title: 分页
  #           name: Pagination
  #         - title: 步骤条
  #           name: Steps
  #         - title: 标签页
  #           name: Tabs
